language: ruby
before_install: gem install bundler
bundler_args: --without guard metrics
script: "bundle exec rake spec"
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx
  - jruby-head
  - ruby-head

notifications:
  email:
    - piotr.solnica@gmail.com
