sudo: false
cache: bundler
language: ruby
bundler_args: --without guard metrics
env:
  - CODECLIMATE_REPO_TOKEN=ac43bd25904f09e52ef2c9f43d3618f7ca52ad9b2103e007f9a3c4da58a04071
script: "bundle exec rake spec"
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email:
    - piotr.solnica@gmail.com
